import './globals.css'
import type { Metadata } from 'next'
import { Inter, Manrope } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import Footer from './components/footer/Footer'
import localFont from '@next/font/local';
import {Providers} from './GlobalRedux/provider'
import { store } from './GlobalRedux/store'
const inter = Inter({ subsets: ['latin'] })


export const monumentum = localFont({
  src: [
    {
      path: '../../public/fonts/MonumentExtended-Regular.ttf',
      weight: '400'
    },
  ],
  variable: '--font-momentum'
})

export const satoshiVariable = localFont({
  src: [
    {
      path: '../../public/fonts/FontsFree-Net-Satoshi-Variable.ttf',
      weight: '400'
    },
  ],
  variable: '--font-satoshi'
})



export const manrope = Manrope({ subsets: ['latin'] })
 const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      {/* <Navbar/> */}
      <body className={`${inter.className}`}>
   <Providers>
   {children}
    </Providers>        
        </body>
      {/* <Footer/> */}
    </html>
  )
}
